# Generated by Django 5.1.3 on 2024-11-22 09:14

import auths.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_meal_user_mobile_user_phone_address_comment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='img_url',
            field=models.ImageField(blank=True, null=True, storage=auths.storage.MealStorage, upload_to='images'),
        ),
    ]
