# Generated by Django 5.1.3 on 2024-11-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_meal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
