# Generated by Django 5.1.3 on 2024-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_alter_meal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
