# Generated by Django 5.1.3 on 2024-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_meal_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
