# Generated by Django 5.1.3 on 2024-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_alter_order_is_delivered_alter_order_is_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
