# Generated by Django 5.1.3 on 2024-12-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0012_alter_order_date_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
    ]
