# Generated by Django 5.1.3 on 2024-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0013_rename_user_id_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
