# Generated by Django 5.1.3 on 2024-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_alter_meal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='inProgress', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='shipping',
            field=models.FloatField(default=0, max_length=7),
        ),
    ]
