# Generated by Django 5.1.3 on 2024-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0015_alter_order_state_alter_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
