# Generated by Django 5.1.3 on 2024-12-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0017_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
