# Generated by Django 5.1.3 on 2025-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0018_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
    ]
