# Generated by Django 5.1.3 on 2025-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0019_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='time_create',
            field=models.DateField(blank=True, null=True),
        ),
    ]
