# Generated by Django 5.1.3 on 2025-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0020_meal_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
