# Generated by Django 5.1.3 on 2025-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0022_discount_userdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='usage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
